(load (concat user-emacs-directory "elpaca"))
(load (concat user-emacs-directory "evil"))
(load (concat user-emacs-directory "keys"))
(load (concat user-emacs-directory "ui"))
(load (concat user-emacs-directory "org"))
(load (concat user-emacs-directory "completion"))
(load (concat user-emacs-directory "packages"))
(load (concat user-emacs-directory "buffer-move"))
